image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  image: docker:stable
  services:
   - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS
  script:
    - echo 'Build'
    - docker build -t $DOCKER_REPO_USER/reddit reddit/
    - docker push $DOCKER_REPO_USER/reddit

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
    - echo "$CI_PRIVATE_KEY" | tr -d '\r' > /tmp/.id_rsa
    - chmod 600 /tmp/.id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add /tmp/.id_rsa
    - ssh -o stricthostkeychecking=no $CI_USER@$HOST sudo docker run -d --restart unless-stopped --log-driver json-file --log-opt max-size=200m -p 9292:9292 --name reddit $DOCKER_REPO_USER/reddit
  environment:
    name: dev
    url: http://$HOST:9292

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.co
