dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: TUFjzJn2k5r1kH29HIKXE6GiuVB3JgtzKdnXo2SGFDmk4siLLbtgMC8tA48S3PsGRm5WMau33OBT9yMiDOKN+j1eYOSHMwzt5zzx+Yx0OBwQFq8i1DjaX2bZnP23DKTWtL2vq4ZVPxepQB2QmtMuaMZ3Fydz/QKQ00PAFBG2+xYDyFJEXLnrUIGdJtCVSEg7zEtaHla1iMqCMrJarnsjKye7IlikLmjI7Nmcu9Oq/nsJPquoZwhwWm2fnqQZVbtDx12Ee7fXHr+cExYGfoW7VMgEvWO0FGxRWysn2pUCXH4bQOc9kDbMB4njkFJUyBQlhPZKFGVmXRceZFQPdqM1eFD2qgSCzyUI8cPeeXFLQbslNET1autJzh3HmBnEOOF7VZ/c3v7J8pXJeawVErBUqG22zRwzvsO7ByflNRWjuAi5oW0uhMFohJ6pE3QBJ54XLOrtPt0mMmovMa0RXOWyhfQXuFiLQWqQCAkoom7cobDgPtIyyXpeMtXO6FaNmXVYQ59gpfMzYlCv+7ejLjTXsQROzTfIFGf1/BXBZTflmKe5k3B5W4X6WB8ZCCpyHH4XK5/h1jYRN9/s920tPtFn7wMapIT/6J02QWPXO/SxhYcf1ooay12uM5yos2CWFs472cHCS3o1tB4Zpyz6HfYFCr0wzk0I/mQGfXoxSSOZJXs=
