---
# установка docker и если определены: docker-compose/docker-machine
- name: Install docker
  hosts: all:!ungrouped
  become: true

  pre_tasks:
    - name: Set Linux Mint facts
      vars:
        fact_base_os: "{{ lookup('file', '/etc/upstream-release/lsb-release') }}"
      set_fact:
        #Для отдельной задачи pre_tasks: Return base OS of Linux Min
        #  command: cat /etc/upstream-release/lsb-release
        #  register: fact_base_os
        #ansible_distribution: "{{ fact_base_os.stdout| regex_search('DISTRIB_ID=([^\n]+)', '\\1')|first| lower }}"
        #ansible_distribution_release: "{{ fact_base_os.stdout| regex_search('DISTRIB_CODENAME=([^\n]+)', '\\1')|first| lower }}"

        #Для переменной в этой же задаче
        #  fact_base_os: "{{ lookup('file', '/etc/upstream-release/lsb-release') }}"
        ansible_distribution: "{{ fact_base_os| regex_search('DISTRIB_ID=([^\n]+)', '\\1')|first|lower }}"
        ansible_distribution_release: "{{ fact_base_os| regex_search('DISTRIB_CODENAME=([^\n]+)', '\\1')|first| lower }}"
      when:
        ansible_facts['distribution'] == "Linux Mint"
    - debug: msg="Set distribution - {{ ansible_distribution }} / {{ ansible_distribution_release }}"

  roles:
  - docker
