---
apiVersion: v1
kind: Service
#name - уникальное имя ресурса, указываем релиз в метке
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  # поды только этого релиза
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
