version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.0
    expose:
      - 9200
    ports:
      - "9200:9200"


  kibana:
    image: kibana:6.8.0
    ports:
      - "5601:5601"
