version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${APP_UI_VERSION}
    command: ["puma", "--debug", "-w", "2"]
    ports:
      - ${APP_UI_PORT}:9292/tcp
    networks:
      - front_net
    volumes:
      - /app/ui:/app

  post:
    build: ./post-py
    image: ${USERNAME}/post:${APP_POST_VERSION}
    networks:
      - back_net
      - front_net
    volumes:
      - /app/post-py:/app

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${APP_COMMENT_VERSION}
    command: ["puma", "--debug", "-w", "2"]
    networks:
      - back_net
      - front_net
    volumes:
      - /app/comment:/app

volumes:
  post_db:

networks:
  back_net:
  front_net:
